# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lyd/udpwifi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lyd/udpwifi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyd/udpwifi/CMakeFiles /home/lyd/udpwifi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lyd/udpwifi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named udpwifi

# Build rule for target.
udpwifi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udpwifi
.PHONY : udpwifi

# fast build rule for target.
udpwifi/fast:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/build
.PHONY : udpwifi/fast

CDatabase.o: CDatabase.cc.o
.PHONY : CDatabase.o

# target to build an object file
CDatabase.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDatabase.cc.o
.PHONY : CDatabase.cc.o

CDatabase.i: CDatabase.cc.i
.PHONY : CDatabase.i

# target to preprocess a source file
CDatabase.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDatabase.cc.i
.PHONY : CDatabase.cc.i

CDatabase.s: CDatabase.cc.s
.PHONY : CDatabase.s

# target to generate assembly for a file
CDatabase.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDatabase.cc.s
.PHONY : CDatabase.cc.s

CDbConnection.o: CDbConnection.cc.o
.PHONY : CDbConnection.o

# target to build an object file
CDbConnection.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbConnection.cc.o
.PHONY : CDbConnection.cc.o

CDbConnection.i: CDbConnection.cc.i
.PHONY : CDbConnection.i

# target to preprocess a source file
CDbConnection.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbConnection.cc.i
.PHONY : CDbConnection.cc.i

CDbConnection.s: CDbConnection.cc.s
.PHONY : CDbConnection.s

# target to generate assembly for a file
CDbConnection.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbConnection.cc.s
.PHONY : CDbConnection.cc.s

CDbResult.o: CDbResult.cc.o
.PHONY : CDbResult.o

# target to build an object file
CDbResult.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbResult.cc.o
.PHONY : CDbResult.cc.o

CDbResult.i: CDbResult.cc.i
.PHONY : CDbResult.i

# target to preprocess a source file
CDbResult.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbResult.cc.i
.PHONY : CDbResult.cc.i

CDbResult.s: CDbResult.cc.s
.PHONY : CDbResult.s

# target to generate assembly for a file
CDbResult.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CDbResult.cc.s
.PHONY : CDbResult.cc.s

CObject.o: CObject.cc.o
.PHONY : CObject.o

# target to build an object file
CObject.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CObject.cc.o
.PHONY : CObject.cc.o

CObject.i: CObject.cc.i
.PHONY : CObject.i

# target to preprocess a source file
CObject.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CObject.cc.i
.PHONY : CObject.cc.i

CObject.s: CObject.cc.s
.PHONY : CObject.s

# target to generate assembly for a file
CObject.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/CObject.cc.s
.PHONY : CObject.cc.s

UdpDecoder.o: UdpDecoder.cc.o
.PHONY : UdpDecoder.o

# target to build an object file
UdpDecoder.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/UdpDecoder.cc.o
.PHONY : UdpDecoder.cc.o

UdpDecoder.i: UdpDecoder.cc.i
.PHONY : UdpDecoder.i

# target to preprocess a source file
UdpDecoder.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/UdpDecoder.cc.i
.PHONY : UdpDecoder.cc.i

UdpDecoder.s: UdpDecoder.cc.s
.PHONY : UdpDecoder.s

# target to generate assembly for a file
UdpDecoder.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/UdpDecoder.cc.s
.PHONY : UdpDecoder.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/udpwifi.dir/build.make CMakeFiles/udpwifi.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... udpwifi"
	@echo "... CDatabase.o"
	@echo "... CDatabase.i"
	@echo "... CDatabase.s"
	@echo "... CDbConnection.o"
	@echo "... CDbConnection.i"
	@echo "... CDbConnection.s"
	@echo "... CDbResult.o"
	@echo "... CDbResult.i"
	@echo "... CDbResult.s"
	@echo "... CObject.o"
	@echo "... CObject.i"
	@echo "... CObject.s"
	@echo "... UdpDecoder.o"
	@echo "... UdpDecoder.i"
	@echo "... UdpDecoder.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

